### ISSUE TITLE
ヘッダの変更の表示の遅れについて

### ISSUE THREAD

**Issue by Mimori256** [itsu-dev/modern-manaba#1]
ヘッダをDOMで新しく更新する際に、もとのヘッダが一瞬表示されてしまっています。
対処として、元ヘッダの読み込み→更新の間、一時的にページを表示しないなどの方法が考えられるので、参考までにPRを挙げます。

**Comment by itsu-dev** [comment]
https://github.com/itsu-dev/modern-manaba/commit/b40e243af129a846e06551b8ec5d1c8e7f99dc6e
