### ISSUE TITLE
コースページでメニューのcssが読み込まれない

### ISSUE THREAD

**Issue by Mimori256** [itsu-dev/modern-manaba#10]
![image](https://user-images.githubusercontent.com/80367947/151662322-e4bb32e5-aec3-4146-a950-1918f65342bf.png)
コースページでcore.cssが読み込まれていないため、小テストやアンケートのcssが適用されていません。

**Comment by itsu-dev** [comment]
確認します！

**Comment by itsu-dev** [comment]
https://github.com/itsu-dev/modern-manaba/commit/645b2f2833db2b68e0bf21639f238138212baad8
で修正しましたが、スタイルに問題が残っているためissueは継続します

**Comment by Mimori256** [comment]
これ個人的に思ったんですが、core.cssのコースメニューに関わるCSSをheader.cssに移すのじゃだめなんですかね？コースメニューがあるかないかの判定はheader.jsでされますし。

**Comment by itsu-dev** [comment]
確かに、そのようにしたほうがいいかもしれませんね...対応お願いしてもいいですか？

**Comment by itsu-dev** [comment]
https://github.com/itsu-dev/modern-manaba/pull/12
