### ISSUE TITLE
未提出課題ページで緑がmanaba Enhanced for Tsukubaと干渉する

### ISSUE THREAD

**Issue by kzsh4124** [itsu-dev/modern-manaba#14]
![image](https://user-images.githubusercontent.com/49474508/152524365-dba5f4ff-f118-470b-b249-f178e6b61dcb.png)
この拡張機能は使っている人が多そうなので干渉しないように調整したほうが良いと思いました。
未提出課題のページだけは白と緑のストライプにしないなどの対応が手っ取り早いと思います。

**Comment by itsu-dev** [comment]
https://github.com/itsu-dev/modern-manaba/pull/15
