### ISSUE TITLE
リリースに必要なアセットの用意

### ISSUE THREAD

**Issue by Mimori256** [itsu-dev/modern-manaba#17]
そろそろ完成に近づいてきた気がするので一応書いておきます。  
Chrome Storeで拡張機能を公開するには、いくつかの画像が必要なのでまとめておきます。
* ストアページ用の、128x128のアイコン
* 1280x800 か 640x400のスクリーンショット

他に、今回初めて拡張機能を公開するには、5ドルかかります。

**Comment by itsu-dev** [comment]
了解です！
デベロッパー登録と含めて近いうちに準備しておきます

**Comment by itsu-dev** [comment]
完了
