### ISSUE TITLE
小テスト・アンケート・ドリルのUIについて

### ISSUE THREAD

**Issue by itsu-dev** [itsu-dev/modern-manaba#22]
小テスト、アンケート、ドリルのUIについては、オンライン試験時にこの拡張を入れている人とそうでない人との公平性を期すため、独自デザインを適用しない方向にしたいと思うのですがどうでしょうか。もしこの場合には、該当ページでのダークモードの適用もなしにしたいです。

**Comment by itsu-dev** [comment]
@Mimori256

**Comment by Mimori256** [comment]
試験時の公平性ですか、全く考えていませんでした。とりあえず独自デザインを適用しない形で進めていいと思います！

**Comment by itsu-dev** [comment]
了解です！
