### ISSUE TITLE
The reason the dark mode not using `prefers-color-scheme`?

### ISSUE THREAD

**Issue by yudukikun5120** [itsu-dev/modern-manaba#29]
Is there a reason the dark mode does not follow the browser's prefers-color-scheme value? It should be better to do that.
If nothing, I'd open the PR.

**Comment by Mimori256** [comment]
I guess there's no specific reason for that
but gotta confirm that first @itsu-dev

**Comment by itsu-dev** [comment]
There is no reason for not following prefers-color-scheme.
We are ready for your PR!

**Comment by yudukikun5120** [comment]
@itsu-dev
Sorry for confusing you. PR #31 does not relate to this issue, it Is just a pre-procedure to development.
Could I ask you to re-open this issue?
