### ISSUE TITLE
コースメニューの未提出数の表示について

### ISSUE THREAD

**Issue by Mimori256** [itsu-dev/modern-manaba#7]
![image](https://user-images.githubusercontent.com/80367947/151307906-f31f70a6-5ae1-43f8-ae9e-ff21acf3ac17.png)
この画像の"1"の部分が表示されるようにしたい。HTML的にはクラスネームがmy-unreadcountのspanタグの中に未提出数が記されているという感じになっています

**Comment by Mimori256** [comment]
実験してみたら取得意外と簡単そうなのでやってみます

**Comment by itsu-dev** [comment]
https://github.com/itsu-dev/modern-manaba/pull/9
